### PR TITLE
Added new db tables to Chat

### PR DESCRIPTION
**Pull request by DinoPuller**
Added migrate20180301-ZimbraChat.pl script

### CODE REVIEW

**Comment by Prashantsurana** [comment]
can you please sign CLA?

**Comment by jiteshsojitra** [comment]
We need to increment number in server/java code as well.

**Comment by DinoPuller** [comment]
Ok here's the pull-request https://github.com/Zimbra/zm-mailbox/pull/559

**Comment by gordyt** [comment]
Created `feature/chat` based on current `develop` that container this PR commit(s) as follows:


    git fetch origin
    git checkout -B develop origin/develop
    git fetch https://github.com/DinoPuller/zm-build develop
    cat .git/FETCH_HEAD
    efbc91086927382be4744cd4178ad4569d526a22                branch 'develop' of https://github.com/DinoPuller/zm-build
	
Investigate:

    git lalw efbc91086927382be4744cd4178ad4569d526a22

    *  efbc91086 [Dino Puller] Added migrate20180301-ZimbraChat.pl script
    *  5e62cf56e [Rupali Desai] (origin/to_be_deleted) ZCS-4223 Adding new version of bcprov-jdk15on

Note that this pull request is no longer correctly based on origin/develop. Fixing…

    git checkout -B feature/chat develop
    git cherry-pick efbc91086

View results

    git lalw feature/chat
    *  2c3415034 [Dino Puller] (HEAD -> feature/chat) Added migrate20180301-ZimbraChat.pl script
    *  b2ee4be69 [Travis McLane] (origin/develop, origin/HEAD, develop) ZCS-4381 inject 'zimbra-attrs-shema' into zimbraLDAPSchemaVersion

Is good now. Publish:

	git push origin feature/chat

**Note:**


The git alias I was using is defined as follows:

	lalw = log --graph --decorate --pretty='format: %Cblue%h%Creset [%an]%Cred%d %Cgreen%s' --abbrev-commit

**Comment by gordyt** [comment]
This commits from this pull request have been rebased and merged to `develop`. Closing pull request.

**Pull request closed without merging**
