### PR TITLE
Added BUILD_BRANCH for repo specification

### PR DESCRIPTION
**Pull request by gordyt**
This change was backported from `feature/imap`.  If this PR is approved, there is a similar one that I will submit for `zm-network-build`.

The bulk of the repos required for a build checkout the same branch. This change allows one to specify that branch in one place.  Only deviations from that need to be specified individually.

### CODE REVIEW

**Comment by fatkudu** [comment]
I certainly like the idea of eliminating as much need for changes as possible.  If what @shri314 says means we don't even need to touch files, at all, so much the better.

**Comment by gordyt** [comment]
Thank you Shriram!  I will update zm-build PR to implement your suggestion.

**Comment by grishick** [comment]
I think it would be helpful to have the repo list in a standard format rather than a perl script, so that any other script can use the repo list if needed. E.g., we may need to create more release management and gitflow utilities and they could read the repo list from zm-build and/or zm-network-build.

**Comment by gordyt** [comment]
I am closing this PR to address @shri314 comments and also investigate an alternate format for the repo lists in `zm-build` and `zm-network-build` to make them easier to use by various scripts we may write to manage large collections of repositories.

**Pull request closed without merging**
