### PR TITLE
ZCS-3812 : Create a utility for Contact backup

### PR DESCRIPTION
**Pull request by chinmay15**
Added zmcontactbackup to be picked up in the build.

Linked PR  -
https://github.com/Zimbra/zm-backup-utilities/pull/1
https://github.com/Zimbra/zm-core-utils/pull/16

### CODE REVIEW

**Comment by Prashantsurana** [comment]
Is it network addition feature or foss? 
This repo is network.

**Comment by gordyt** [comment]
@chinmay15 Subject to @Prashantsurana 's question (and the request I made in the linked PR), the change seems fine. I do note that [zm-backup-utilities](https://github.com/Zimbra/zm-backup-utilities) is a private repo and this change is inserted into the `NETWORK` build type section.

**Comment by chinmay15** [comment]
Changed repo from zm-backup-utilities to zm-core-utils. Please review.

**Comment by chinmay15** [comment]
merged into develop

commit eef7e1a886e7bb8a58ca89696f2e3075cd33ae6f
Author: Chinmay Pathak <15.chinmay@gmail.com>
Date:   Fri Mar 23 12:34:27 2018 +0100

    ZCS-3812 : Create a utility for Contact backup

**Pull request closed without merging**
